"""
User authentication module with password change and reset functionality.
Password reset is an extended (admin-level) privilege.
"""

import hashlib
import secrets
import string


ROLE_USER = "user"
ROLE_ADMIN = "admin"

# In-memory user store: {username: {"password_hash": str, "role": str, "reset_token": str|None}}
_users: dict = {}


def _hash_password(password: str) -> str:
    """Return a SHA-256 hex digest of the given password."""
    return hashlib.sha256(password.encode()).hexdigest()


def _generate_token(length: int = 32) -> str:
    """Generate a secure random token."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def register_user(username: str, password: str, role: str = ROLE_USER) -> None:
    """Register a new user with the given username, password, and role."""
    if username in _users:
        raise ValueError(f"User '{username}' already exists.")
    if role not in (ROLE_USER, ROLE_ADMIN):
        raise ValueError(f"Invalid role '{role}'. Must be '{ROLE_USER}' or '{ROLE_ADMIN}'.")
    _users[username] = {
        "password_hash": _hash_password(password),
        "role": role,
        "reset_token": None,
    }


def authenticate(username: str, password: str) -> bool:
    """Return True if the username and password are correct."""
    user = _users.get(username)
    if user is None:
        return False
    return user["password_hash"] == _hash_password(password)


def change_password(username: str, old_password: str, new_password: str) -> None:
    """
    Allow an authenticated user to change their own password.
    Raises ValueError if authentication fails or user does not exist.
    """
    if not authenticate(username, old_password):
        raise ValueError("Authentication failed: incorrect username or password.")
    if not new_password:
        raise ValueError("New password must not be empty.")
    _users[username]["password_hash"] = _hash_password(new_password)


def generate_reset_token(admin_username: str, admin_password: str, target_username: str) -> str:
    """
    Extended (admin-only) privilege: generate a one-time reset token for target_username.
    The requesting user must be authenticated and have the admin role.
    Returns the reset token string.
    """
    if not authenticate(admin_username, admin_password):
        raise ValueError("Authentication failed: incorrect admin credentials.")
    admin = _users.get(admin_username)
    if admin["role"] != ROLE_ADMIN:
        raise PermissionError(
            f"User '{admin_username}' does not have permission to reset passwords. "
            "Admin role required."
        )
    if target_username not in _users:
        raise ValueError(f"Target user '{target_username}' does not exist.")
    token = _generate_token()
    _users[target_username]["reset_token"] = token
    return token


def reset_password(target_username: str, reset_token: str, new_password: str) -> None:
    """
    Reset the password for target_username using a valid reset token.
    The token must have been previously generated by an admin via generate_reset_token().
    Raises ValueError if the token is invalid or the user does not exist.
    """
    user = _users.get(target_username)
    if user is None:
        raise ValueError(f"User '{target_username}' does not exist.")
    if not user["reset_token"] or user["reset_token"] != reset_token:
        raise ValueError("Invalid or expired reset token.")
    if not new_password:
        raise ValueError("New password must not be empty.")
    user["password_hash"] = _hash_password(new_password)
    user["reset_token"] = None  # Invalidate token after use


def get_user_role(username: str) -> str:
    """Return the role of the given user."""
    user = _users.get(username)
    if user is None:
        raise ValueError(f"User '{username}' does not exist.")
    return user["role"]
